# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getting_time', models.DateTimeField(auto_created=True)),
                ('image', models.ImageField(max_length=255, upload_to=b'images')),
                ('time_of_end_converting_job', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
